"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  ADMIN_DASHBOARD_PATH,
  ADMIN_LOGIN_PATH,
  ADMIN_MFA_ENROLL_PATH,
} from "@/lib/admin-path";
import { Button, LinkButton } from "@/components/site/button";
import { getBrowserClient } from "@/lib/supabase/browser-client";
import { cn } from "@/lib/utils";

/**
 * TOTP challenge (client island). Lists the user's verified TOTP factors,
 * challenges one, and verifies the 6-digit code. On success the session is
 * AAL2 and the user is routed to the admin dashboard.
 *
 * IMPORTANT UX: This system uses TOTP (authenticator apps like Google
 * Authenticator, Authy, 1Password) — NOT email or SMS. The 6-digit code comes
 * FROM the user's authenticator app, not from a message we send. If the user
 * has no enrolled factor, we send them to the enrollment page (which shows a
 * QR code to scan with their app).
 */
export function MfaChallengeForm({ configured }: { configured: boolean }) {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [noFactor, setNoFactor] = useState(false);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!configured) {
      setError("Authentication isn't configured in this environment.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const client = getBrowserClient();
      const { data: factors, error: listError } =
        await client.auth.mfa.listFactors();
      if (listError || !factors?.totp?.length) {
        setNoFactor(true);
        return;
      }
      const factor = factors.totp[0]!;
      const challenge = await client.auth.mfa.challenge({ factorId: factor.id });
      if (challenge.error) {
        setError("Could not issue an MFA challenge.");
        return;
      }
      const verifyRes = await client.auth.mfa.verify({
        factorId: factor.id,
        challengeId: challenge.data.id,
        code: code.trim(),
      });
      if (verifyRes.error) {
        setError("Invalid code. Try again.");
        return;
      }
      // Keep spinner spinning during navigation (no setLoading(false) on success).
      router.push(ADMIN_DASHBOARD_PATH);
      router.refresh();
    } catch {
      setError("Verification failed.");
      setLoading(false);
    }
    // No finally: on success, spinner stays until navigation completes.
  }

  if (!configured) {
    return (
      <p className="t-body-sm text-ink-secondary">
        Authentication isn't configured in this environment, so the MFA
        challenge can't run.
      </p>
    );
  }

  if (noFactor) {
    return (
      <div className="flex flex-col gap-5">
        <div className="flex flex-col gap-2 rounded-md border border-line bg-surface p-4">
          <p className="t-body text-ink">
            You haven't set up an authenticator yet.
          </p>
          <p className="t-body-sm text-ink-secondary">
            This admin area requires a Time-based One-Time Password (TOTP) from
            an authenticator app like <strong>Google Authenticator</strong>,{" "}
            <strong>Authy</strong>, <strong>1Password</strong>, or{" "}
            <strong>Microsoft Authenticator</strong>. No codes are sent to you
            by email or SMS — the code is generated by the app on your phone.
          </p>
        </div>
        <LinkButton href={ADMIN_MFA_ENROLL_PATH} size="lg" className="w-full">
          Set up my authenticator
        </LinkButton>
        <button
          type="button"
          onClick={() => router.push(ADMIN_LOGIN_PATH)}
          className="t-caption text-ink-secondary underline underline-offset-4 hover:text-ink text-center"
        >
          Back to login
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={onSubmit} className="flex flex-col gap-4" aria-busy={loading || undefined}>
      <div className="flex flex-col gap-1.5">
        <label htmlFor="mfa-challenge-code" className="t-label text-ink">
          6-digit code
        </label>
        <input
          id="mfa-challenge-code"
          name="code"
          inputMode="numeric"
          autoComplete="one-time-code"
          pattern="[0-9]{6}"
          required
          disabled={loading}
          value={code}
          onChange={(e) => setCode(e.target.value)}
          className={cn(
            "h-11 rounded-md border border-line-strong bg-canvas px-3 t-body text-ink tracking-widest text-center",
            "transition-[border-color,opacity] duration-[var(--duration-fast)]",
            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
            "disabled:opacity-60 disabled:cursor-not-allowed",
          )}
          placeholder="000000"
        />
        <p className="t-caption text-ink-muted">
          Open your authenticator app and enter the current 6-digit code.
        </p>
      </div>
      {error ? <p role="alert" className="t-body-sm text-danger">{error}</p> : null}
      <Button type="submit" loading={loading} className="w-full">
        {loading ? "Verifying…" : "Verify"}
      </Button>
      <button
        type="button"
        onClick={() => router.push(ADMIN_LOGIN_PATH)}
        className={cn(
          "t-caption text-ink-secondary underline underline-offset-4 hover:text-ink text-center",
          "transition-opacity duration-[var(--duration-fast)]",
          loading && "pointer-events-none opacity-50",
        )}
      >
        Back to login
      </button>
    </form>
  );
}
